### ISSUE TITLE
[bug] dstoolbox has errors with sklearn 0.19

### ISSUE THREAD

**Issue by benjamin-work** [ottogroup/dstoolbox#17]
There have been some interface changes in sklearn that lead to errors in dstoolbox. For instance, `_transform_one`, as used by `DataFrameFeatureUnion`, now accepts only 3 arguments instead of 4. Presumably, there are other areas that might fail.

**Comment by BenjaminBossan** [comment]
Should be fixed by https://github.com/ottogroup/dstoolbox/pull/18
