### ISSUE TITLE
Strict requirements prevent package upgrade

### ISSUE THREAD

**Issue by fcharras** [ottogroup/dstoolbox#28]
The strict requirements versions yield a warning when upgrading dstoolbox with more recent dependencies, like sklearn 19.2:

```dstoolbox 0.6.2 has requirement scikit-learn==0.19, but you'll have scikit-learn 0.19.2 which is incompatible.```

**Comment by benjamin-work** [comment]
I agree that that this error should not occur. dstoolbox accesses some private functions from sklearn, so it is liable to break when sklearn updates, but patch level updates should be relatively safe.

Could you please tell me how you triggered the error?

**Comment by benjamin-work** [comment]
@fcharras I have deployed a new dstoolbox version, 0.6.5, on pypi, hopefully that solves the issue.

**Comment by fcharras** [comment]
I triggered the error during an offline install in a venv, following https://stackoverflow.com/questions/11091623/python-packages-offline-installation

I'm testing 0.6.5

**Comment by fcharras** [comment]
It seems the error is gone. Thanks!
